name: sqs-daemon

on:
  workflow_dispatch:
  push:
    branches:
    - main
  
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Restore Dependencies
        working-directory: src
        run: dotnet restore SQSDaemon.sln

      - name: Build Solution
        working-directory: src
        run: dotnet build SQSDaemon.sln --configuration Release --no-restore
      
      - name: Run Tests
        working-directory: src
        run: dotnet test SQSDaemon.sln --configuration Release --no-restore --verbosity normal
